name: lamb2fetch
on: [push, workflow_dispatch]
permissions:
 contents: write
jobs:
 fetch:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: curl
     run: |
      mkdir -p out
      curl --max-time 360 --connect-timeout 120 -L -A 'Mozilla/5.0' 'https://moderngov.lambeth.gov.uk/ieListDocuments.aspx?CId=116&MId=17395' > out/l17395.html &
      curl --max-time 360 --connect-timeout 120 -L -A 'Mozilla/5.0' 'https://moderngov.lambeth.gov.uk/ieListDocuments.aspx?CId=600&MId=17465' > out/l17465.html &
      curl --max-time 360 --connect-timeout 120 -L -A 'Mozilla/5.0' 'https://moderngov.lambeth.gov.uk/ieListDocuments.aspx?CId=733&MId=17451' > out/l17451.html &
      curl --max-time 360 --connect-timeout 120 -L -A 'Mozilla/5.0' 'https://moderngov.lambeth.gov.uk/ieListDocuments.aspx?CId=115&MId=17474' > out/l17474.html &
      wait
      ls -l out
   - name: commit
     run: |
       git config user.email act@example.com; git config user.name act; git add out; git commit -m lambout || true; git push origin lambfast
