name: fetch
on: [push, workflow_dispatch]
permissions:
 contents: write
jobs:
 fetch:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: curl
     run: |
      mkdir -p out
      curl -L --retry 3 -A 'Mozilla/5.0' 'https://democracy.wandsworth.gov.uk/ieListDocuments.aspx?CId=792&MId=10266' > out/cab.html
      curl -L --retry 3 -A 'Mozilla/5.0' 'https://democracy.wandsworth.gov.uk/ieListDocuments.aspx?CId=763&MId=9927' > out/grants.html
      curl -L --retry 3 -A 'Mozilla/5.0' 'https://democracy.wandsworth.gov.uk/ieListDocuments.aspx?CId=305&MId=10010' > out/standards.html
      curl -L --retry 3 -A 'Mozilla/5.0' 'https://democracy.wandsworth.gov.uk/ieListDocuments.aspx?CId=511&MId=10115' > out/sacre.html
      ls -l out
   - name: commit
     run: |
       git config user.email act@example.com; git config user.name act; git add out; git commit -m out || true; git push
